id: A8E56A8AD
title: Lamp Aspiration Prayer (from the Tsok Offering 'A Rain of Blessings')
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:19:08.480302
  last_modified_at: 2022-02-28 23:19:08.480309
