id: A8E56A8AD
title: Prayer for the Land of Great Bliss Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:19:08.482128
  last_modified_at: 2022-02-28 23:19:08.482132
